# Generated by Django 4.2.5 on 2023-09-25 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(default="", upload_to="Photo")),
                ("title", models.CharField(max_length=1000)),
                ("slug", models.CharField(default="", max_length=1000)),
                ("content", ckeditor.fields.RichTextField()),
                ("publish", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("short_detail", models.CharField(max_length=1000)),
                ("tag", models.ManyToManyField(to="blog.tag")),
            ],
        ),
    ]
